### ISSUE TITLE
Bot stopped updating but Magnus keeps playing

### ISSUE THREAD

**Issue by twinysam** [mrvlasyuk/catch_magnus#2]
Hey there,

Awesome bot which has been especially great to catch up on Magnus's online adventures in the early days of lockdown. But unfortunately it has stopped working. Last update was on May 10, but Magnus has been playing on Lichess as recently as [5 days ago](https://lichess.org/8M7oCD2n).

I'm not really a programmer, but I would imagine this may have had to do with some change in Lichess API or something like that?

Anyway, it'd be awesome to have this neat bot working again. Thanks for the good work!

**Comment by twinysam** [comment]
Hmm, seems to be working again all of a sudden. Strange, but great!

**Comment by mrvlasyuk** [comment]
I restarted it after your comment. So thank you 👍
